Adanos020/egui_dock

README.md
examples/hello.rs
examples/simple.rs
src/lib.rs
src/style.rs
src/tab.rs
src/tree.rs

`Tab` is no longer a trait which the user has to implement on their own custom widget. A context type is also no longer required.
This makes creating trees easier without limiting customizability.
Example:
```rust
// Initial tree setup
let tab1 = TabBuilder::default()
.title("Tab 1")
.content(|ui| {
ui.label("Tab 1");
})
.build();
let tab2 = TabBuilder::default()
.title("Tab 2")
.inner_margin(Margin::same(4.0))
.content(|ui| {
ui.label("Tab 2");
})
.build();
let mut tree = Tree::new(vec![tab1, tab2]);
// Then, in your app's `update` function:
egui_dock::show(&mut ui, id, &style, &mut tree)
```
Part of this PR is closing #1 and #5

`Tab` rewrite

---

Cargo.toml
examples/hello.rs
examples/simple.rs
src/lib.rs
src/tab.rs

The `WithTitle` trait is redundant since `WidgetText` already implements `From` for various types.
This PR also bumps egui to the latest version (0.18 -> 0.19).

Replace `WithTitle` trait with `impl Into<WidgetText>`

---

CHANGELOG.md
README.md
examples/hello.rs
examples/simple.rs
examples/traits.rs
src/lib.rs
src/style.rs
src/tab.rs
src/tree.rs

Added the ability for tabs to be closed.
There are two ways a tab can be closed. either a user presses the close button and the `on_close` function returns true. or if the tab returns true from its `force_close` function that is called every frame.
The docking area will also now keep track of the currently "focused" leaf. This allows for tabs to be appended with `push_to_active_leaf`. if there is no currently focused leaf the function will add the tab to the first leaf it finds or crate a new leaf.
when tabs are dragged onto a new leaf they will be set as the active tab.
tabs can now also be reordered by dragging over existing tabs. dropping while over an existing tab will insert the new tab into its index pushing tabs to the right of it over (also making that index the active index).
You …

Added the ability to close tabs

---

CHANGELOG.md
README.md
examples/hello.rs
examples/simple.rs
examples/traits.rs
src/lib.rs

Changes : 
- Does not own Tree
- Does not need to be stored
- Use a builder style API to change the id, the style and show with ctx or inside an ui

Change `DockArea` api to look a bit more like other egui containers

---

CHANGELOG.md
README.md
examples/hello.rs
examples/simple.rs
examples/text_editor.rs
examples/traits.rs
src/dynamic_tab.rs
src/lib.rs
src/tab.rs
src/tree.rs

The current `trait Tab` implementation has some limitations:
A) We cannot serialize `Tree`:s.
B) One must create the tabs up-front with everything they need to show themselves (with `Tab::ui`).
The second point in particular impose very weird constraints on users. If a tab wants to modify some global state, it need to be initialized with a `Arc<Mutex<State>>` or similar. I don't like!
This PR is a refactor that solves both these problems (and more!?).
The approach is this: instead of storing a `Box<dyn Tab>` in `Tree`, we instead make `Tree` generic over what the user wants to identify a tab (`Tree<Tab>`). For instance, a user may identify each tab by a UUID or similar. Then we use a new `trait TabView` which actually shows the tabs, fetches their titles, handles close events, and so on. …

Refactor: TabViewer

---

CHANGELOG.md
Cargo.toml
src/tree.rs

Allows users to persist the `Tree` layout

Add opt-in serde feature to enable serialization of Tree

---

CHANGELOG.md
src/style.rs
src/tree.rs

Previously the tab text color was always a weird green.
This was due to a bit of (very) unintuitive egui API (sorry!): unless a color is set in `WidgetText`, the default text color is an ugly shade of green to remind you to set a color.

Fix tab text color

---

src/dynamic_tab.rs
src/lib.rs

This lets you have a tab that isn't rendered by egui, but instead e.g. by the underlying game engine:

add ability to disable the background clear color for a tab

---

src/lib.rs
src/style.rs
src/tree.rs

Currently I am making extensive use of `egui_dock` in my application, but I found that it was missing several features that would have improved my quality of life vastly. This is a PR with 3 of such improvements:
* `StyleBuilder::from_egui` - Initializes the inner `Style` of `StyleBuilder` through `Style::from_egui`.
* Having multiple Docks, even with different `id`s caused clashes in the id space (even if I used `ui.push_id`). This change makes the  id sources of several elements factor in the Dock's own `id` to prevent clashes.
* Pictured above is two separate docks :)
* `Tree::find_active_focused` - The tree exposed `find_active`, but it did not expose the same funcitonality when there are potentially multiple splits. This change introduces `find_active_focused` to do exactly that. …

StyleBuilder::from_egui, multiple dock IDs, Tree::find_active_focused

---

examples/hello.rs
src/lib.rs
src/style.rs

Closes #44.
I added an option to Style and added a checkbox to the `hello` example to demonstrate its use.
For #43, the calculation of `expanded_width` in `lib.rs` will need tweaking to subtract the width of the add-tab button from the available width, which should be painless. If that gets merged first I can update this PR as appropriate.

Add option to expand tabs to fill tab bar

---

CHANGELOG.md
src/style.rs

Followup from #45. I didn't notice the new option should be added to `StyleBuilder`, and also updated the changelog to mention the new option.

Add expand_tabs to StyleBuilder and update CHANGELOG

---

examples/hello.rs
src/lib.rs
src/style.rs

This makes the ScrollArea inside tabs optional via Style 
#48

Make ScrollArea optional via Style

---

src/lib.rs
src/style.rs

Previously, you would have `CursorIcon::PointingHand` when hovering a tab title. When dragging a tab, you would get `CursorIcon::Grabbing`, but if you dragged a tab so it was hovering another title, it would go back to `CursorIcon::PointingHand`.
This PR changes the hovering cursor to `CursorIcon::Grab`. Additionally, it fixes the above bug so that `CursorIcon::Grabbing` is used all the while a tab is being dragged.

Fix: use the correct icon when dragging

---

CHANGELOG.md
src/tree.rs

Lets users iterate over the tabs in a `Tree`.

Add `Tree::tabs`: an iterator over the tabs

---

CHANGELOG.md
examples/hello.rs
src/lib.rs
src/style.rs

Might be useful when #42 is implemented and names aren't fully visible meanwhile it's default is set to false

added hover shows tab name when style enabled

---

src/style.rs

This PR changes the cursor use for the close button. Previously the drag hand icon was used, which is confusing and incorrect, since you can't actually drag a tab from the close button.
I also found it a bit hard sometimes to determine whether the cursor was currently hovering over the close button because the drag hand is so wide, so I changed it to the pointing hand.
Before:
After:
Alternatively, the standard arrow cursor might be used, which is what firefox and chromium do. But they also use the arrow for the rest of the tab until you start dragging it, so ¯\\\_(ツ)_/¯

Better cursor for close button

---

src/lib.rs

The `TabIndex` is used within the public interface of the crate, however the type itself was not pub.
I also had to change the order of imports a bit because `utils::*` seems to include the type somehow.
That resulted in the type still being inaccessible and the explicit pub use of TabIndex being marked as an "unused import".

Make TabIndex publically accessible

---

examples/tab_add.rs
src/lib.rs
src/style.rs

Currently if you enable expand-tabs and also show-add-tab-button the tabs expand into the space for the button, which also means their close button overlaps the add button. We discussed this a bit in #44 but because #45 was merged before #43 it didn't include the fix, which I've made here.
I added expand-tabs to the `tab_add` example so that it's easier to see how it works:

Fix combining 'expand tabs' and 'show add tab button'

---

examples/tab_add_popup.rs
src/lib.rs
src/popup.rs
src/style.rs

This PR creates an `add_popup` method in `egui_dock::TabViewer`, which enables context-menu-like popups when clicking the add button. This is useful for selecting one of multiple tab types to add. 
There's a usage example:
```
cargo run --example tab_add_popup
```
It uses a custom version of `egui`'s `popup_below_widget` because that implementation will fall outside of the window if it's near the bottom or right edge. The code for that comes from https://github.com/emilk/egui/pull/1653#issuecomment-1133671051. All credit for it goes to @zicklag.

Implement add popups

---

CHANGELOG.md
src/lib.rs
src/style.rs

Fixes(?) https://github.com/Adanos020/egui_dock/issues/64
It seems that this is enough for the inner_margin setting to work in the examples.
There are a few more places (Tab, TabBuilder), but they are marked #[deprecated]

inner_margin in Style

---

CHANGELOG.md
examples/hello.rs
src/lib.rs
src/style.rs
src/tree.rs
src/utils.rs

The separator by default have the same color as the panel separators in egui

Change separator color on hover and drag

---

CHANGELOG.md
examples/hello.rs
src/tree.rs

I wanted to be able to add/remove tabs in different parts of the gui (i.e. in a View menu). The add is already supported with push_to_focused_leaf, but the remove was not available as an API call. I was able to find it in the render logic and put it in its own function and I thought this might be useful for other people.
toggled on:
toggled off:
Edit:
Also it wasn't something I could easily add as a utility function in my own code since `TabIndex` isn't publicly accessible. Looks like that's fixed in #60 though, so I don't need this merged if you guys think it's not something you want to add.

Added ability to remove tab (using logic from render)

---

src/tree.rs

The `#[derive(Default)]` requires that the `Tab` parameter implements `Default`.
Solution: manual default impl.

Don't require `Tab: Default` for `Tree<Tab>: Default`

---

src/lib.rs

Fixes #92.
Noticed the same problem occurred for `middle_clicked` close functionality so fixed it as well.

fix: allow tabs to be clicked when tabs-are-draggable is false

---

examples/hello.rs
src/lib.rs
src/style.rs

A default style is barely different, but this PR makes it a lot more customizable
Before:
After:
Oh, and the style editor in the `hello` example looks much nicer:

More customaizable tabs

---

examples/hello.rs
src/lib.rs

Using `max_rect()` in `DockArea::show_inside` function makes the DockArea hide any element previously added, it is specially annoying when using Panels.
With the following code:
```rust
CentralPanel::default().show(ctx, |ui| {
TopBottomPanel::top("top_bar").show_inside(ui, |ui| {
ui.label("MyLabel");
});
DockArea::new(&mut self.tree)
.show_inside(ui, &mut self.context);
});
```
We previously had:
And with this change we have:

Use available_rect_before_wrap() in DockArea::show_inside

---

src/lib.rs

Fixes what we can for #95.
Currently, egui does not support well the addition of a 'background' layer (it makes `is_pointer_over_area`) break (see issue for details).
In this PR I propose creating a `CentralPanel` instead to circumvent the issue. 
However, in my opinion we shouldn't have a show function which takes a `Context`, we're trying to do the same thing as a `CentralPanel` without the ability to interact with egui's internals.
I think that we could consider `DockArea` as a Widget, which has to be rendered inside an egui Ui. In this case we could only have a `show` function that would be the equivalent of today's `show_inside`. I agree that intuitively, DockArea is a Container, but in the egui sense, it would avoid the issue pointed in #95.
What are your thoughts @Adanos020?

Use CentralPanel in DockArea::show()

---

CHANGELOG.md
src/style.rs

Fixes (#91).
No need for internal state like suggested in the issue :relaxed:

fix splitter drag behavior

---

examples/hello.rs

Reverts a part of the changes made to the hello example in #102
It seems the line that was setting the style on the MyContext struct was inadvertently removed causing the style editor tab to panic when shown, since style was None and it unwraps it. 
I also removed the line from that PR that manually set the `selection_color` to BLUE as it's already a semi-transparent blue by default and it seems better to showcase the default values. If there was a reason for this lmk, it just seemed like it was just mistakenly left in since there wasn't any discussion about it.

Fix style editor in hello example

---

src/lib.rs
src/style.rs
src/tree.rs

I added `#![warn(missing_docs)]` so that we do not forget to document new elements in the future.

Add #![warn(missing_docs)] flag to lib and small doc tweaks

---

CHANGELOG.md
examples/hello.rs
src/lib.rs
src/style.rs
src/tree.rs

Looking into `Tree` structure, I found the method `remove_empty_leaf` which:
- Didn't seem like something useful for external users
- Was always used in contexts where we knew the actual `NodeIndex` that could be removed, causing a useless linear search.
So I removed the function and replaced it with the more useful `remove_leaf` function.
I also removed a bit of duplicated code regarding tab removal.
To simplify a bit the `DockArea::show_inside` I extracted the tab moving logic inside the `Tree` structure as the `Tree::move_tab` function.

Improve Node management 

---

CHANGELOG.md
examples/hello.rs
src/lib.rs
src/style.rs
src/tree.rs
src/utils.rs

Attempt to fix #42 by making tab bar scroll-able (with mouse wheel) when tabs overflow.
This is very much work in progress as it does not handle expand tab option and likely won't work on touch devices.

make tabs scrollable when there are too many

---

src/style.rs

Proposed fix for #111, using the same color as `tabs.bg_fill`, only a little darker.
Dark Theme:
Light Theme:

make tab bar default bg opaque, a bit darker than active tab

---

src/style.rs

@Adanos020, here's a little fix that I missed in my scroll bar PR.

fix tab add button not sensing click

---

CHANGELOG.md
src/lib.rs

This PR is meant to ensure that each tab has its own egui::Id and that it is preserved when moving the tab around in the DockArea. This is really important to make sure egui memory is carried when the tab is moved. For instance, a `egui::Plot` zoom will have a different zoom saved for each possible tab location.
By default, the tab title is used as a source of unique id but the user can define a custom behavior with the new `TabViewer::id()` method.

add id() method to TabViewer trait

---

CHANGELOG.md
src/widgets/dock_area/mod.rs

Fix close button hidden when tab bar too small

---

CHANGELOG.md
src/tree/mod.rs
src/widgets/dock_area/mod.rs

Fixes #133.
I moved computation of Rect sizes before drawing any part of the UI.
I though that the convention of how right/left children map to top/bottom was a bit blurry. So I made sure that:
- left/right children are left/right node when drawn.
- left/right children are top/bottom node when drawn.
I'm not sure how it was previously but I think it simplifies the code in `duplicate!`.

compute rect sizes before drawing bodies

---

CHANGELOG.md
Cargo.toml
src/widgets/dock_area/mod.rs

Fixes #142 
The bug and the fix are trivial:
```rs
fn allocate_area_for_root(&mut self, ui: &mut Ui) {
let style = self.style.as_ref().unwrap();
let mut rect = ui.available_rect_before_wrap();
if let Some(margin) = style.dock_area_padding {
rect.min += margin.left_top();
rect.max -= margin.right_bottom();
ui.painter().rect(
rect,
margin.top,
style.separator.color_idle,
Stroke::new(margin.top, style.border.color),
);
}
if self.tree.is_empty() {
ui.allocate_rect(rect, Sense::hover()); // <------ THIS SHOULDN'T BE IN THIS BRANCH
return;
}
self.tree[NodeIndex::root()].set_rect(rect);
}
```

Always allocate area for the `DockArea`.

---

README.md
src/widgets/dock_area/mod.rs

double clicking on the separator will now reset the fraction to 0.5, this behaviour is consistent with other docking tools like VSCode.

feat: double click on separator to reset size

---

examples/hello.rs
src/style.rs
src/widgets/dock_area/hover_data.rs
src/widgets/dock_area/mod.rs
src/widgets/mod.rs

I have a use case where I never ever want the user to be able to make vertical splits. This PR allows the programmer to disable vertical or horizontal splits via `allowed_splits` on the `Style` struct.

feat: allow disabling vertical/horizontal splits

---

CHANGELOG.md
examples/hello.rs
src/widgets/dock_area/mod.rs
src/widgets/tab_viewer.rs

﻿Closes #113
Mandatory requirements (see [CONTRIBUTING.md](../CONTRIBUTING.md)):
The close button and context menu item is now only shown if `TabViewer::closable` returns true. A default implementation is provided that always return true. No default behaviour have changed
Here only the "Inspector" tab is not closable:

Allow individual tabs to be closable or not

---

examples/hello.rs
src/widgets/dock_area/mod.rs
src/widgets/tab_viewer.rs

I use the `context_menu(...)` function so display options for splitting the current window. To call the `split(...)` function, I need to know the `parent` node. However this is not available at the moment.
I tried using the `focused_leaf(...)` function, but depending on the mouse position the split goes into the wrong parent.
Pass the `NodeIndex` to the `context_menu(...)` function, the same way as it is done in the `on_add` function.

Add the NodeIndex to context_menu() parameter list

---

README.md

It would be nice to list egui_tiles as an alternative 
Here is the [comparision](https://github.com/rerun-io/egui_tiles#comparison-with-egui_dock)

Add egui tiles as alternative in readme

---

CHANGELOG.md
examples/hello.rs
examples/reject_windows.rs
examples/simple.rs
examples/tab_add.rs
examples/tab_add_popup.rs
examples/text_editor.rs
src/widgets/dock_area/show/leaf.rs
src/widgets/tab_viewer.rs

Make `TabViewer::{on_add,add_popup} accept corresponding surface index

---

src/widgets/dock_area/show/leaf.rs

fixes bug  #168, by always ignoring window hovers when the dragging tab a non window tab. This fades all windows and only allows main surface leaves to gather "preference" from the dragged tab.

Fix for bug #168

---

src/widgets/dock_area/show/mod.rs

Fixes #172 
removes the a check that prevented users from rearranging tabs in the node they reside in. 
Now in order for the user to "regret" a move in the middle of an undock while in the widgeted overlay style would be to move the tab to the center overlay icon.

Fix for issue #172

---

src/widgets/dock_area/drag_and_drop.rs
src/widgets/dock_area/show/mod.rs
src/widgets/dock_area/state.rs

fixes issue #174 by removing the use of ``Instant`` inside the drag/drop state. As methods like ``Instant::now()`` is not implemented for wasm. This has been replaced with ``egui::InputState::time`` instead.

Fix for issue #174

---

src/dock_state/mod.rs
src/widgets/dock_area/show/leaf.rs
src/widgets/dock_area/show/mod.rs

Fixes two minor bugs found with dragging and droppping tabs.
1.Dragging a tab from a window with a single tab to an empty surface causes a panic
Steps to reproduce:
* dragging each tab from a dock state into a window
* drag one of the tabs out to create a second window
* take the single tab from the second window and put it into the empty surface
2.Dragging a tab and pressing new mouse buttons causes unintended behavior
Steps to reproduce:
* drag any tab
* press any secondary mouse button while dragging
both of these have been fixed by restricting drags to only be carried out by the primary mouse button and restructuring code to properly delete empty assets from the tree (unless they're explicitly meant to be like eg. an empty surface)

Misc. fixes of two bugs regarding dragging tabs

---

src/widgets/dock_area/show/leaf.rs
src/widgets/dock_area/show/mod.rs
src/widgets/dock_area/state.rs

Makes the dock work on mobile devices with wasm. Closes #179 
I was not sure where to put the assignment of the `state.hover_pos`. I ended up putting it inside the `show_leaf` function.
If there is a better place, please feel free to tell me where.

Fix hover_pos on touch screens

---

src/widgets/dock_area/show/leaf.rs

This fixes  #183, although I am not 100% sure if this is the correct approach.

fix: Fix Tab not respecting background clearing

---

CHANGELOG.md
Cargo.toml
src/widgets/dock_area/show/leaf.rs

Patch 0.7.3: Hide the 'Eject' button if a tab isn't allowed in windows

---

CHANGELOG.md
Cargo.toml
README.md
src/dock_state/window_state.rs
src/style.rs
src/widgets/dock_area/drag_and_drop.rs
src/widgets/dock_area/show/leaf.rs
src/widgets/dock_area/show/mod.rs
src/widgets/tab_viewer.rs

The primary purpose of this release is upgrading to egui 0.23.
- Upgraded `egui` to version 0.23.
- Updated MSRV to Rust 1.70.
- Revised documentation for `TabViewer`.

Release 0.8

---

CHANGELOG.md
Cargo.toml
src/widgets/dock_area/show/leaf.rs

Fixes #190 
Basically, in `DockArea::tab_bar_scroll`, the scrolling coefficient is determined by a calculation which involves division by the available width. The problem is that when the available width is 0, the division results in infinity which is later multiplied by 0, and that produces a NaN here:
```rs
*scroll -= scroll_bar_handle_response.drag_delta().x * points_to_scroll_coefficient;
```
The `scroll` coefficient is later used all over the tab bar code, which spreads the NaN like a disease.
My fix for this is basically just turning off all tab bar code when the width is 0.
I also did a bit of clean-up: the `Response` returned from `DockArea::tab_bar` is only ever used to obtain the occupied `Rect`, so I made the function just return the `Rect` instead.

Prevent division by zero when tab bar width is 0

---

CHANGELOG.md
src/dock_state/mod.rs
src/dock_state/surface.rs
src/dock_state/tree/mod.rs
src/dock_state/tree/node.rs
src/dock_state/tree/tab_iter.rs

Closes #192 and #194 
This adds more convenient iterators, renames some for clarity, and removes those that can be created just as easily by other means.
Full change list:
- `DockArea::surfaces_count`
- `DockArea::iter_surfaces[_mut]`
- `DockArea::iter_all_tabs[_mut]`
- `DockArea::iter_all_nodes[_mut]`
- `Node::iter_tabs[_mut]`
- `Surface::iter_nodes[_mut]`
- `Surface::iter_all_tabs[_mut]`
- Removed the deprecated `DockState::iter`
- `DockState::iter_nodes` – use `iter_all_nodes` instead.
- `DockState::iter_main_surface_nodes[_mut]` – use `dock_state.main_surface().iter()` (and corresponding `mut` versions) instead.

Iterators overhaul

---

CHANGELOG.md
Cargo.toml
src/dock_state/tree/mod.rs
src/dock_state/window_state.rs

Fixes #197 
Make sure to fix your last serialized app state by setting `screen_rect: null`.

Fix deserialization of `WindowState::screen_rect` when it contains any `f32::INFINITY` values.

---

src/dock_state/mod.rs
src/dock_state/surface.rs
src/dock_state/tree/mod.rs
src/dock_state/tree/node.rs

This PR implements a `map` function for all types containing tabs.
The concept is similar to the map function in `Iterator`s, `Result`s, `Option`s, etc, taking a closure which receives a value and returns a new one, possibly of a different type.
Since serde deserialization does not allow partial deserialization or passing additional values, this feature can be used to construct the tab types from intermediate deserialized values while mixing in things like shared pointers.
```rs
let some_non_deserializable_value = Arc::new(..);
let tree: Tree<serde_json::Value> = from_str(..).unwrap();
let tree = tree.map_tabs(|value| {
ActualTabType::new(some_non_deserializable_value.clone(), value).unwrap()
});
```
Also see https://github.com/Adanos020/egui_dock/pull/196#issuecomment-1786986562

Mapping over tab types

---

CHANGELOG.md
Cargo.toml
README.md
examples/hello.rs
src/dock_state/mod.rs
src/dock_state/surface.rs
src/dock_state/tree/mod.rs
src/dock_state/tree/node.rs
src/dock_state/tree/tab_iter.rs
src/dock_state/window_state.rs

- `DockArea::surfaces_count`
- `DockArea::iter_surfaces[_mut]`
- `DockArea::iter_all_tabs[_mut]`
- `DockArea::iter_all_nodes[_mut]`
- `Node::iter_tabs[_mut]`
- `Surface::iter_nodes[_mut]`
- `Surface::iter_all_tabs[_mut]`
- Upgraded to egui 0.24.
- Removed the deprecated `DockState::iter`.
- `DockState::iter_nodes` – use `iter_all_nodes` instead.
- `DockState::iter_main_surface_nodes[_mut]` – use `dock_state.main_surface().iter()` (and corresponding `mut` versions) instead.

Release 0.9

---

src/dock_state/mod.rs
src/dock_state/tree/mod.rs

Fixes #206 
Deleting the last tab from a window surface using `DockState::remove_tab` doesn't delete the surface, which causes applications to crash on the following frame where `DockArea` attempts to render an empty window.
Solution: remove the window surface if its `Tree` is empty.

Fix crash after calling `DockState::remove_tab`.

---

CHANGELOG.md
Cargo.toml
README.md
src/dock_state/mod.rs
src/dock_state/tree/mod.rs
src/style.rs
src/widgets/dock_area/show/leaf.rs
src/widgets/dock_area/show/mod.rs

This pull request closes #207 by fixing the behaviour of keyboard focus when using the Tab key on the keyboard.
I also added highlighting to the buttons in the tab titles when they are focused with the keyboard, and added the ability to change the current tab by focusing it with the keyboard and then pressing Enter or Space.
If you want me to update the changelog, let me know what I should put for the version.

Keyboard focus fixes

---

CHANGELOG.md
src/dock_state/mod.rs
src/dock_state/translations.rs
src/lib.rs
src/widgets/dock_area/show/leaf.rs
src/widgets/dock_area/show/window_surface.rs

Adds missing translation, and also replaces `Default` implementation for the translation types with associated functions called `english`.

Add window tooltip translation

---

CHANGELOG.md
Cargo.toml
README.md
src/dock_state/mod.rs
src/dock_state/translations.rs
src/lib.rs
src/style.rs
src/widgets/dock_area/show/leaf.rs
src/widgets/dock_area/show/mod.rs
src/widgets/dock_area/show/window_surface.rs

- From ([#211](https://github.com/Adanos020/egui_dock/pull/211)):
- Tabs, the close tab buttons and the add tab buttons are now focusable with the keyboard and interactable with the enter key and space bar.
- Separators are now focusable with the keyboard and movable using the arrow keys while control or shift is held.
- `TabStyle::active_with_kb_focus`, `TabStyle::inactive_with_kb_focus` and `TabStyle::focused_with_kb_focus` for style of tabs that are focused with the keyboard.
- Missing translation for the tooltip showing when you hover on a grayed out window close button. ([#216](https://github.com/Adanos020/egui_dock/pull/216))
- Widgets inside tabs are now focusable with the tab key on the keyboard. ([#211](https://github.com/Adanos020/egui_dock/pull/211))
- Upgraded to egui 0.25
- …

Release 0.10

---

CHANGELOG.md
Cargo.toml
src/widgets/dock_area/show/main_surface.rs

Fix docking on empty main surface.

---

CHANGELOG.md
src/dock_state/tree/mod.rs

`filter_map_tabs` sometimes deletes nodes when it shouldn't. This is a fix for that.

Fix `filter_map_tabs`

---

CHANGELOG.md
Cargo.toml
src/widgets/dock_area/show/leaf.rs
src/widgets/popup.rs

As title says:
After the fix the background is rounded with the value of `TabBodyStyle::rounding`.

Fix tab body background not being rounded

---

CHANGELOG.md
Cargo.toml
README.md
examples/hello.rs
examples/simple.rs
src/style.rs
src/widgets/dock_area/drag_and_drop.rs
src/widgets/dock_area/mod.rs
src/widgets/dock_area/show/leaf.rs
src/widgets/dock_area/show/main_surface.rs
src/widgets/dock_area/show/mod.rs

- Upgraded to egui 0.27.
- All `Style` structs are now serializable with `serde`. ([#227](https://github.com/Adanos020/egui_dock/pull/227))
- Dragging tabs around should no longer cause the `DockArea` to resize a tiny bit on every frame.
- Dragged tabs should now always follow the mouse exactly.

Release 0.12

---

CHANGELOG.md
src/dock_state/mod.rs
src/dock_state/surface.rs
src/dock_state/tree/mod.rs
src/dock_state/tree/node.rs

No point of having a FnMut if it can't mutably reference stuff outside

Remove `Clone` bound on `map_tabs` and `filter_map_tabs`

---

Cargo.toml

After this change, `egui_dock` no will no longer have a duplicate dependency on syn (1.x and 2.x)

Update duplicate to 2.0

---

CHANGELOG.md
Cargo.toml
README.md
src/dock_state/mod.rs
src/dock_state/surface.rs
src/dock_state/tree/mod.rs
src/dock_state/tree/node.rs
src/widgets/dock_area/show/leaf.rs
src/widgets/dock_area/show/window_surface.rs

- Upgraded to egui 0.29.
- `{DockState,Surface,Tree,Node}::{filter_map_tabs,map_tabs,filter_tabs,retain_tabs}` no longer require the predicate to
implement `Clone`. ([#241](https://github.com/Adanos020/egui_dock/pull/241))

Release 0.14

---

.gitignore
CHANGELOG.md
Cargo.toml
README.md
examples/hello.rs
src/dock_state/mod.rs
src/dock_state/translations.rs
src/dock_state/tree/mod.rs
src/dock_state/tree/node.rs
src/dock_state/tree/tab_iter.rs
src/dock_state/window_state.rs
src/lib.rs
src/style.rs
src/widgets/dock_area/drag_and_drop.rs
src/widgets/dock_area/mod.rs
src/widgets/dock_area/show/leaf.rs
src/widgets/dock_area/show/main_surface.rs
src/widgets/dock_area/show/mod.rs
src/widgets/dock_area/show/window_surface.rs
src/widgets/dock_area/tab_removal.rs

- From ([#237](https://github.com/Adanos020/egui_dock/pull/237)):
- Each leaf can now be collapsed / closed individually. They are introduced as additional tab bar controls.
- Undocked windows are now more compact. The original undocked window controls are now accessible as "secondary buttons" from the tab bar.
- By default, the secondary buttons are activated from primary buttons either by holding the <kbd>Shift</kbd> key while clicking on them, or from a context menu by right-clicking them.
- A number of tooltip hints are on by default as guides to the new behavior, but they can be disabled.
- There has been an overhaul to the internal codebase to support the new features.
- From ([#237](https://github.com/Adanos020/egui_dock/pull/237)):
- `DockArea::show_leaf_close_all_buttons` – shows …

Release 0.15

---

CHANGELOG.md
Cargo.toml
README.md
examples/hello.rs
src/style.rs
src/widgets/dock_area/drag_and_drop.rs
src/widgets/dock_area/show/leaf.rs
src/widgets/dock_area/show/mod.rs
src/widgets/dock_area/show/window_surface.rs

Things seems to work, but I've never used egui or this crate until today, but I needed a version that works with egui 0.31 so here we are...
* compilation errors 'fixed' - mostly due to changes for the missing stroke kind on rectangles, I used 'StrokeKind::Inside' everywhere.
* all 'deprecated' warnings removed.
* tests pass
* examples run
* changes formatted using `cargo fmt`.
Most of the changes are relating to CornerRadius changes.

Update egui to 0.31

---

Cargo.toml
examples/save_load_dock_state.rs
src/widgets/dock_area/show/leaf.rs
src/widgets/tab_viewer.rs

This PR introduces:
- `on_rect_changed` callback to `TabViewer` to allow users to track when the rect changes.
- An example demonstrating saving and loading the dock state.
- Added `on_rect_changed` callback to `TabViewer`
- Implemented an example for persistent dock states
This feature is useful for handling layout changes and persisting user layouts.
- Tested with the example provided.

feat: add on_rect_changed callback and example for dock state

---

examples/hello.rs
examples/simple.rs
src/dock_state/mod.rs
src/widgets/dock_area/show/leaf.rs
src/widgets/dock_area/show/mod.rs
src/widgets/dock_area/tab_removal.rs
src/widgets/tab_viewer.rs

Ensures that `TabViewer::on_close` is always called on all closable tabs when the user tries to close them. The only exception where `on_close` is not called is when a tab is closed forcefully via `TabViewer::force_close`.

Fix `TabViewer::on_close`

---

src/widgets/dock_area/show/leaf.rs

The close button was using the `style.buttons.add_tab_bg_fill` and while the associated `style.buttons.close_tab_bg_fill` was unused in the layout.

Use close_tab_bg_fill for close buttons

---

src/dock_state/mod.rs

Prevent `DockState::retain_tabs` from deleting main surface

---

src/dock_state/tree/mod.rs

There is a subtle bug, either in `remove_leaf` or `retain_tabs` depending on how you look at it.
When removing leafs, it's possible to leave trailing `Node::Empty` items in the list.  For example, after shuffling tabs around, I found a node list of
```json
"nodes": [
{
"Leaf": { "(elided)" }
},
"Empty",
"Empty",
"Empty",
"Empty",
"Empty",
"Empty"
],
```
I'm not sure if this is a bug or not; it depends on the invariants associated with the `nodes` list.
However, it interacts poorly with the call to `balance` at the end of `retain_tabs`: when `balance` deletes an emptied node, it marks that node's parent for deletion if the node's children are both empty.  Both children of the `Leaf` are empty, so it deletes the leaf as well, even if it should be retained!
This PR updates `remove_leaf` to …

Fix `retain_tabs` behavior with `Empty` nodes in the list
